language: python
python:
  - 2.7
before_install:
  - wget https://bitbucket.org/pypy/pypy/get/default.tar.bz2 | tar xf - rpython
  - ls
install:
  - pip install -Ur test-requirements.txt twisted
  - pip install -e .
script:
  - trial cycy
  - python rpython/bin/rpython --batch --output=cycy-c cycy/target.py
  - python rpython/bin/rpython --batch --output=cycy-c --opt=jit cycy/target.py
