language: python
python:
  - pypy
install:
  - pip install -U pip
  - pip install -Ur test-requirements.txt twisted
  - pip install -e .
script:
  - trial cycy
  - rpython --batch --output=cycy-nojit cycy/target.py
  - rpython --batch --output=cycy-jit --opt=jit cycy/target.py
