language: python
python:
  - pypy
install:
  - pip install -Ur test-requirements.txt twisted
  - pip install -e .
script:
  - trial cycy
  - rpython --batch --output=cycy-nojit cycy/target.py
  - rpython --batch --output=cycy --opt=jit cycy/target.py
